services:
  database:
    image: postgres:15.3 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
  redis-db:
    image: redis:7.4.0
    ports:
      - ${REDIS_PORT}:6379 
    volumes:
      - ./redis:/data

  