interface SeedArticle {
	title: string;
	description: string;
	thumbnail: string;
	priority: number;
	readingTime: number;
	content: string;
	showAds: boolean;
	verticalAds: 'LEFT' | 'RIGHT' | 'NONE';
	horizontalAds: boolean;
	visibleForUsers: boolean;
	creatorId: string;
	category: string;
	slug: string;
	createdAt: Date;
}

/* 
    Seed articles generated by ChatGPT.
*/
export const seedArticles: SeedArticle[] = [
	{
		title: 'The Future of Quantum Computing',
		description: 'Exploring how quantum computing is set to revolutionize various industries.',
		thumbnail: '/images/dev/test-image-1.jpg',
		priority: 3,
		readingTime: 5,
		content: `
## The Future of Quantum Computing

### What is Quantum Computing?

Quantum computing is poised to revolutionize industries by solving complex problems that classical computers cannot handle. Unlike traditional computers that use bits to process information, quantum computers use quantum bits (qubits), allowing for exponentially greater computational power.

### Potential Applications

Quantum computing has the potential to disrupt fields like cryptography, drug discovery, and financial modeling. For instance, quantum algorithms could solve calculations in seconds that would take classical computers thousands of years.

### Challenges Ahead

Despite its promise, quantum computing faces significant challenges, including high error rates and the need for ultra-cold environments. As the technology matures, the possibilities seem endless, but widespread adoption is still years away.
		`,
		showAds: true,
		verticalAds: 'LEFT',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '47c2e21f-71d3-46cb-8bdc-c094567d4e88',
		category: 'technology',
		slug: 'the-future-of-quantum-computing',
		createdAt: new Date(),
	},
	{
		title: 'The Rise of Artificial Intelligence in Politics',
		description: 'How AI is influencing modern political campaigns and decision-making.',
		thumbnail: '/images/dev/test-image-2.jpg',
		priority: 1,
		readingTime: 4,
		content: `
## The Rise of Artificial Intelligence in Politics

### AI in Campaign Strategies

Artificial Intelligence (AI) is becoming a powerful tool in modern politics. From data analysis to voter targeting, AI is changing how campaigns are run. Politicians now use AI algorithms to predict voter behavior and tailor their messages more effectively.

### Ethical Concerns

While AI offers efficiency, it also raises ethical questions. The use of AI in politics can lead to issues like voter manipulation and privacy invasion. Critics argue that AI might deepen divisions in society by reinforcing biases through its algorithms.

### The Future of AI in Politics

As AI continues to evolve, its role in politics will likely expand. However, balancing technological advancements with ethical considerations will be crucial in shaping the future of political AI.
		`,
		showAds: true,
		verticalAds: 'RIGHT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '123ad26d-99a8-4ccd-820c-ce9816effe0a',
		category: 'politics',
		slug: 'the-rise-of-ai-in-politics',
		createdAt: new Date(),
	},
	{
		title: 'Global Economic Outlook 2024',
		description: 'An analysis of the global economic trends and forecasts for 2024.',
		thumbnail: '/images/dev/test-image-3.jpg',
		priority: 2,
		readingTime: 6,
		content: `
## Global Economic Outlook 2024

### Economic Recovery Post-Pandemic

As the world continues to recover from the COVID-19 pandemic, 2024 is expected to be a year of cautious optimism. Economists predict moderate growth across major economies, driven by consumer spending and government stimulus packages.

### Inflation Concerns

However, inflation remains a significant concern. Central banks worldwide are grappling with rising prices, and there is a delicate balance between controlling inflation and supporting economic growth.

### Key Sectors to Watch

Sectors such as technology, renewable energy, and healthcare are expected to see substantial investment. These industries are likely to drive economic growth as countries focus on innovation and sustainability in a post-pandemic world.
		`,
		showAds: true,
		verticalAds: 'NONE',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '94fb31a6-fdd3-49ca-8c02-e001b5303157',
		category: 'economics',
		slug: 'global-economic-outlook-2024',
		createdAt: new Date(),
	},
	{
		title: 'The Ethics of Gene Editing in Humans',
		description: 'A deep dive into the ethical implications of gene editing technologies like CRISPR.',
		thumbnail: '/images/dev/test-image-1.jpg',
		priority: 2,
		readingTime: 5,
		content: `
## The Ethics of Gene Editing in Humans

### The Promise of Gene Editing

Gene editing technologies, such as CRISPR, have the potential to eradicate genetic diseases and enhance human capabilities. These innovations could lead to breakthroughs in medicine, agriculture, and even human evolution.

### Ethical Dilemmas

However, the ability to edit the human genome raises profound ethical questions. Concerns include the potential for "designer babies," unintended consequences in the gene pool, and the accessibility of these technologies, which could widen social inequalities.

### Moving Forward

As gene editing technology advances, it is crucial to establish robust ethical frameworks and international regulations. The challenge will be balancing scientific progress with the moral responsibilities it entails.
		`,
		showAds: true,
		verticalAds: 'LEFT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '5a410bc5-da53-438b-8415-ee24f209bc0e',
		category: 'science',
		slug: 'the-ethics-of-gene-editing-in-humans',
		createdAt: new Date(),
	},
	{
		title: 'Blockchain Beyond Cryptocurrency',
		description: 'Exploring the applications of blockchain technology outside of the cryptocurrency space.',
		thumbnail: '/images/dev/test-image-2.jpg',
		priority: 3,
		readingTime: 4,
		content: `
## Blockchain Beyond Cryptocurrency

### What is Blockchain?

Blockchain technology, best known for powering cryptocurrencies like Bitcoin, has far-reaching applications beyond digital currencies. At its core, blockchain is a decentralized ledger that ensures transparency and security in transactions.

### Applications in Various Industries

Industries such as supply chain management, healthcare, and finance are exploring blockchain to improve efficiency and security. For example, in supply chain management, blockchain can track goods from origin to consumer, ensuring authenticity and reducing fraud.

### The Road Ahead

As blockchain technology continues to evolve, its potential uses across different sectors are expanding. However, challenges like regulatory uncertainty and scalability need to be addressed for broader adoption.
		`,
		showAds: false,
		verticalAds: 'RIGHT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '47c2e21f-71d3-46cb-8bdc-c094567d4e88',
		category: 'technology',
		slug: 'blockchain-beyond-cryptocurrency',
		createdAt: new Date('2024-08-04'),
	},
	{
		title: 'Climate Change: A Global Emergency',
		description: 'An urgent look at the current state of climate change and its implications.',
		thumbnail: '/images/dev/test-image-3.jpg',
		priority: 3,
		readingTime: 5,
		content: `
## Climate Change: A Global Emergency

### The Current State of Affairs

Climate change is no longer a distant threat; it is a present-day crisis. Rising global temperatures, melting ice caps, and extreme weather events are just a few indicators of the accelerating pace of climate change.

### Impacts on Society and Economy

The effects of climate change are being felt worldwide, from food insecurity to economic disruptions. Developing countries, in particular, are vulnerable to climate-related disasters, which exacerbate existing social inequalities.

### Calls to Action

Global leaders and activists are calling for immediate and substantial action to combat climate change. This includes reducing greenhouse gas emissions, transitioning to renewable energy, and implementing sustainable practices across all sectors.
		`,
		showAds: true,
		verticalAds: 'NONE',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '47c2e21f-71d3-46cb-8bdc-c094567d4e88',
		category: 'science',
		slug: 'climate-change-global-emergency',
		createdAt: new Date('2024-08-03'),
	},
	{
		title: 'The Role of Big Tech in Modern Elections',
		description: 'Analyzing the influence of big tech companies in shaping electoral outcomes.',
		thumbnail: '/images/dev/test-image-1.jpg',
		priority: 1,
		readingTime: 4,
		content: `
## The Role of Big Tech in Modern Elections

### Influence on Voter Behavior

Big tech companies like Facebook, Google, and Twitter play a significant role in modern elections. Their platforms are used for political advertising, voter outreach, and even disinformation campaigns. The algorithms these companies use can influence voter behavior by amplifying certain messages.

### The Debate Over Regulation

There is an ongoing debate about how much power these companies should have in elections. Some argue for stricter regulations to prevent misuse, while others believe that these platforms are essential for free speech and democracy.

### Looking Forward

As we move into the next election cycles, the role of big tech will continue to be scrutinized. The balance between free expression and preventing harm will be a central issue for policymakers and society at large.
		`,
		showAds: true,
		verticalAds: 'LEFT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '123ad26d-99a8-4ccd-820c-ce9816effe0a',
		category: 'politics',
		slug: 'big-tech-modern-elections',
		createdAt: new Date('2024-08-03'),
	},
	{
		title: 'The Impact of Automation on the Global Workforce',
		description: 'Examining how automation is reshaping jobs and industries worldwide.',
		thumbnail: '/images/dev/test-image-2.jpg',
		priority: 2,
		readingTime: 5,
		content: `
## The Impact of Automation on the Global Workforce

### The Rise of Automation

Automation is transforming industries at an unprecedented rate. From manufacturing to services, machines and algorithms are increasingly taking over tasks that were once performed by humans. This shift promises efficiency and cost savings but comes with significant implications for workers.

### Job Displacement and Creation

While some jobs are at risk of being automated, new roles are also being created in areas like technology and data analysis. However, the transition is not without challenges, as workers need to upskill or reskill to stay relevant in the changing job market.

### The Future of Work

As automation continues to advance, governments and businesses must collaborate to ensure a smooth transition for the workforce. This includes investing in education, training, and social safety nets to support those affected by job displacement.
		`,
		showAds: true,
		verticalAds: 'RIGHT',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '5a410bc5-da53-438b-8415-ee24f209bc0e',
		category: 'economics',
		slug: 'impact-of-automation-on-global-workforce',
		createdAt: new Date('2024-08-03'),
	},
	{
		title: 'The Geopolitics of Renewable Energy',
		description: 'How the shift towards renewable energy is changing global power dynamics.',
		thumbnail: '/images/dev/test-image-3.jpg',
		priority: 3,
		readingTime: 4,
		content: `
## The Geopolitics of Renewable Energy

### The Shift to Renewables

As the world moves away from fossil fuels, renewable energy sources like solar and wind are becoming more critical. This shift is not only about environmental sustainability but also about changing geopolitical power dynamics.

### Changing Power Structures

Countries that have historically depended on oil and gas exports are facing new challenges as demand shifts towards renewable energy. Meanwhile, nations that lead in renewable energy technology are gaining influence in the global arena.

### The Road Ahead

The transition to renewable energy is likely to continue reshaping international relations. As new energy leaders emerge, traditional powers must adapt to maintain their influence in a rapidly changing world.
		`,
		showAds: true,
		verticalAds: 'NONE',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '47c2e21f-71d3-46cb-8bdc-c094567d4e88',
		category: 'politics',
		slug: 'geopolitics-of-renewable-energy',
		createdAt: new Date('2024-08-02'),
	},
	{
		title: 'The Economics of Space Exploration',
		description: 'Analyzing the economic impact of the growing space industry.',
		thumbnail: '/images/dev/test-image-1.jpg',
		priority: 3,
		readingTime: 5,
		content: `
## The Economics of Space Exploration

### A New Frontier for Investment

Space exploration is no longer just the domain of government agencies like NASA. The private sector, led by companies such as SpaceX and Blue Origin, is investing heavily in space travel and technology, marking a new era of commercial space exploration.

### Economic Opportunities

The space industry presents vast economic opportunities, from satellite technology to space tourism. Governments and private companies are racing to capitalize on these opportunities, which could create jobs and drive innovation.

### Challenges and Risks

However, space exploration is not without its risks. The high costs and technical challenges make it a risky investment, and there are concerns about space debris and the environmental impact of increased space activity.
		`,
		showAds: false,
		verticalAds: 'LEFT',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '123ad26d-99a8-4ccd-820c-ce9816effe0a',
		category: 'economics',
		slug: 'economics-of-space-exploration',
		createdAt: new Date('2024-08-02'),
	},
	{
		title: 'The Role of Social Media in Political Polarization',
		description: 'Investigating how social media platforms contribute to political division.',
		thumbnail: '/images/dev/test-image-2.jpg',
		priority: 2,
		readingTime: 4,
		content: `
## The Role of Social Media in Political Polarization

### The Echo Chamber Effect

Social media platforms have become breeding grounds for political polarization. Algorithms designed to maximize engagement often lead users to echo chambers, where they are exposed only to viewpoints that reinforce their existing beliefs.

### The Spread of Misinformation

Misinformation spreads quickly on social media, further exacerbating divisions. False or misleading information can be amplified by algorithms, making it challenging for users to distinguish between fact and fiction.

### Solutions and Future Directions

Addressing political polarization on social media requires a multifaceted approach, including algorithmic transparency, fact-checking initiatives, and digital literacy education. Policymakers and tech companies must work together to mitigate the harmful effects of polarization.
		`,
		showAds: true,
		verticalAds: 'RIGHT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '5a410bc5-da53-438b-8415-ee24f209bc0e',
		category: 'politics',
		slug: 'social-media-political-polarization',
		createdAt: new Date('2024-08-01'),
	},
	{
		title: 'The Science Behind COVID-19 Vaccines',
		description: 'Understanding the technology and research that made COVID-19 vaccines possible.',
		thumbnail: '/images/dev/test-image-3.jpg',
		priority: 3,
		readingTime: 6,
		content: `
## The Science Behind COVID-19 Vaccines

### mRNA Technology

The development of COVID-19 vaccines was a scientific triumph, largely thanks to mRNA technology. Unlike traditional vaccines, which use inactivated viruses, mRNA vaccines teach cells how to produce a protein that triggers an immune response.

### The Speed of Development

The rapid development of COVID-19 vaccines was unprecedented. Decades of research into mRNA technology, coupled with global collaboration and funding, made it possible to create effective vaccines in record time.

### Ongoing Research

Research continues to improve COVID-19 vaccines and adapt them to emerging variants. Scientists are also exploring the potential of mRNA technology for other diseases, which could revolutionize the future of medicine.
		`,
		showAds: true,
		verticalAds: 'NONE',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '47c2e21f-71d3-46cb-8bdc-c094567d4e88',
		category: 'science',
		slug: 'science-behind-covid19-vaccines',
		createdAt: new Date('2024-08-01'),
	},
	{
		title: 'The Economic Impact of Climate Change',
		description: 'Assessing the economic costs and challenges posed by climate change.',
		thumbnail: '/images/dev/test-image-2.jpg',
		priority: 2,
		readingTime: 5,
		content: `
## The Economic Impact of Climate Change

### Rising Costs

Climate change is not just an environmental issue; it has significant economic implications. The increasing frequency of natural disasters, such as hurricanes, floods, and wildfires, leads to costly damages and disrupts economies.

### Effects on Global Markets

Climate change affects global markets by impacting agriculture, infrastructure, and resource availability. For example, changing weather patterns can reduce crop yields, leading to higher food prices and food insecurity.

### Mitigation and Adaptation

To mitigate the economic impact of climate change, investments in renewable energy, sustainable infrastructure, and disaster preparedness are essential. Policymakers must also consider climate risks in economic planning to ensure long-term resilience.
		`,
		showAds: true,
		verticalAds: 'LEFT',
		horizontalAds: false,
		visibleForUsers: true,
		creatorId: '123ad26d-99a8-4ccd-820c-ce9816effe0a',
		category: 'economics',
		slug: 'economic-impact-of-climate-change',
		createdAt: new Date('2024-08-03'),
	},
	{
		title: 'The Ethics of Artificial Intelligence in Healthcare',
		description: 'Exploring the ethical challenges posed by AI in the medical field.',
		thumbnail: '/images/dev/test-image-3.jpg',
		priority: 3,
		readingTime: 5,
		content: `
## The Ethics of Artificial Intelligence in Healthcare

### AI in Diagnosis and Treatment

Artificial Intelligence (AI) is becoming increasingly important in healthcare, from diagnosing diseases to developing personalized treatment plans. While AI has the potential to improve patient outcomes, it also raises significant ethical concerns.

### Privacy and Bias

One of the primary ethical challenges of AI in healthcare is privacy. AI systems often require large amounts of data, which can lead to concerns about patient confidentiality. Additionally, AI algorithms can inherit biases from the data they are trained on, potentially leading to unequal treatment.

### Ethical Frameworks

As AI continues to evolve in healthcare, establishing robust ethical frameworks will be crucial. These frameworks should ensure that AI is used in ways that are transparent, fair, and respectful of patient rights.
		`,
		showAds: true,
		verticalAds: 'RIGHT',
		horizontalAds: true,
		visibleForUsers: true,
		creatorId: '94fb31a6-fdd3-49ca-8c02-e001b5303157',
		category: 'science',
		slug: 'ethics-of-ai-in-healthcare',
		createdAt: new Date('2024-08-03'),
	},
];
